#!/bin/bash
#
# Use wget to mirror a directory.
#

function die {
  echo "$@" 1>&2
  exit 1
}

function usage_die {
  die "$(cat <<USAGE
Usage: $(basename $0) [<wget options>] <start>
Examples:
$(basename $0) https://www.example.com/dir/
  or
$(basename $0) https://www.example.com/start.html
USAGE
)"
}

if [[ -z "$1" ]]; then
  usage_die
fi

#CRAWL_DOMAIN=$(sed -n 's|^.*://\([^/]*\).*$|\1|p' <<<"$CRAWL_START")
#if [[ -z "$CRAWL_DOMAIN" ]]; then
#  usage_die
#fi
#--domains "$CRAWL_DOMAIN"

# Seconds or labeled units. Randomized to 0.5*$WAIT to 1.5*$WAIT with
# --random-wait option. If not specified already, use a very conservative value.
if [[ -z "$CRAWL_WAIT" ]]; then
  CRAWL_WAIT=3m
fi

wget \
  --recursive \
  --level=inf \
  --no-timestamping \
  --no-clobber \
  --no-remove-listing \
  --verbose \
  --no-parent \
  --output-file=/dev/stderr \
  --execute robots=off \
  --user-agent='Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2725.0 Safari/537.36' \
  --page-requisites \
  --wait "$CRAWL_WAIT" \
  --random-wait \
    "$@"
